- name: Import vManage Policy Lists
  hosts: localhost
  connection: local
  roles:
    - ansible-viptela
  vars:
    vmanage_host: "{{ groups.vmanage_hosts | first }}"
    vmanage_ip: "{{ hostvars[vmanage_host].ansible_host }}"
    file: vmanage_central_policy.yml
  gather_facts: no
  tasks:
    - name: Reading file {{ file }}
      include_vars:
        file: "{{ file }}"
        name: vmanage_central_policy

    - debug:
        var: vmanage_central_policy

    - name: Import central policy
      vmanage_central_policy:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        state: present
        aggregate: "{{ vmanage_central_policy.central_policy }}"
      register: policy_facts
#
#    - debug:
#        var: policy_facts

    - name: Activate central policy
      vmanage_central_policy:
        user: "{{ ansible_user }}"
        host: "{{ vmanage_ip }}"
        password: "{{ ansible_password }}"
        state: activated
        wait: yes
        aggregate: "{{ vmanage_central_policy.central_policy }}"
      register: policy_facts

    - debug:
        var: policy_facts