- hosts: network:&virl_hosts
  connection: network_cli
  gather_facts: no
  tags:
    - debug
  vars:
    config_template: "{{ ansible_network_os }}/cli.j2"
  tasks:
  - name: Debug file
    tags:
      - debug
    copy:
      content: "{{ lookup('template', config_template) }}"
      dest: "{{ inventory_hostname }}.cfg"
    delegate_to: localhost

- hosts: network:&virl_hosts
  connection: network_cli
  gather_facts: no
  vars:
    config_template: "{{ ansible_network_os }}/cli.j2"
  tasks:
  - name: Configure network device
    cli_config:
      config: "{{ lookup('template', config_template) }}"
