- name: Configure vmanage
  hosts: vmanage1
  connection: local
  roles:
    - ansible-viptela
  gather_facts: no
  tasks:
    - name: Get device facts
      vmanage_device_facts:
        user: "{{ ansible_user }}"
        host: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
      register: device_facts
      delegate_to: localhost
#      until: (all_vedges | difference(device_facts.vedges | selectattr('site-id','defined') | map(attribute='host-name')) | list | length) == 0
#      retries: 60
#      delay: 10
#      vars:
#        all_vedges: "{{ groups.viptela_vedge | intersect(groups.virl_hosts) }}"

    - debug:
        var: device_facts
#
#    - set_fact:
#        foo: "{{ device_facts.vedges | selectattr('host-name','defined') | map(attribute='host-name') | list }}"
#
#    - debug:
#        var: foo
#
    - debug:
        msg: "All vedges: {{ all_vedges }}"
      vars:
        all_vedges: "{{ groups.viptela_vedge | intersect(groups.virl_hosts) }}"

    - debug:
        msg: "site-id: {{ device_facts.vedges | selectattr('site-id','defined') | map(attribute='host-name') | list }}"

    - debug:
        msg: "{{ all_vedges | difference(device_facts.vedges | selectattr('site-id','defined') | map(attribute='host-name')) | list  }}"
      vars:
        all_vedges: "{{ groups.viptela_vedge | intersect(groups.virl_hosts) }}"