vmanage_ping_tests:
  - dst_ip: 10.22.3.10
    vedge: east-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.23.3.10
    vedge: west-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 10.22.4.10
    vedge: west-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 10.23.4.10
    vedge: west-vedge1
    vpn: 11
    pass: yes
#  - dst_ip: 10.22.3.10
#    vedge: east-vedge1
#    vpn: 11
#    pass: no
#  - dst_ip: 10.23.3.10
#    vedge: east-vedge1
#    vpn: 11
#    pass: yes
#  - dst_ip: 10.22.4.10
#    vedge: east-vedge1
#    vpn: 11
#    pass: yes
#  - dst_ip: 10.23.4.10
#    vedge: east-vedge1
#    vpn: 11
#    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site1-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.18.0.10
    vedge: site1-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.20.1.10
    vedge: site1-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.20.1.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.18.0.10
    vedge: site1-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site2-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.18.0.10
    vedge: site2-vedge1
    vpn: 10
    pass: yes
  - dst_ip: 172.17.0.10
    vedge: site2-vedge1
    vpn: 11
    pass: yes
  - dst_ip: 172.18.0.10
    vedge: site2-vedge1
    vpn: 11
    pass: yes