- name: Update RTBH
  hosts: vmanage1
  connection: local
  roles:
    - ansible-viptela
  vars:
    policy_list_name: blocked_prefixes
    policy_list_entries:
      - ipPrefix: 10.0.1.0/24
      - ipPrefix: 10.0.2.0/24
      - ipPrefix: 10.0.3.0/24
      - ipPrefix: 10.0.4.0/24
      - ipPrefix: 10.0.5.0/24
#      - ipPrefix: 172.18.0.0/16
  gather_facts: no
  tasks:
    - name: Import policy lists
      vmanage_policy_list:
        user: "{{ ansible_user }}"
        host: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        name: "{{ policy_list_name }}"
        entries: "{{ policy_list_entries }}"
        type: dataprefix
        push: yes
      register: policy_list_facts